@extends("layouts.admin")
@section("page-title","Edit IdCard")
@section("content")
<div class="container-fluid py-4"><div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h4 class="fw-bold mb-1"><i class="bi bi-pencil-square me-2"></i>Edit IdCard</h4><nav aria-label="breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}" class="text-decoration-none text-muted">Dashboard</a></li><li class="breadcrumb-item"><a href="{{route('admin.id-cards.index')}}" class="text-decoration-none text-muted">IdCards</a></li><li class="breadcrumb-item active text-gold">Edit</li></ol></nav></div></div>
<form method="POST" action="{{route('admin.id-cards.update',$item->id)}}">@csrf @method('PUT')
<div class="card border-0 shadow-sm"><div class="card-header bg-white py-3" style="border-top:3px solid #c9a84c;"><h5 class="mb-0 fw-semibold">Details</h5></div><div class="card-body"><div class="row g-3"><div class="col-md-6"><label class="form-label fw-medium">Student id</label><input type="text" name="student_id" class="form-control" value="{{$item->student_id}}">@error('student_id')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-6"><label class="form-label fw-medium">Card number</label><input type="text" name="card_number" class="form-control" value="{{$item->card_number}}">@error('card_number')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-4"><label class="form-label fw-medium">Type</label><select name="type" class="form-select"><option value="">Select...</option><option value="student" {{$item->type=='student'?'selected':''}}>Student</option><option value="staff" {{$item->type=='staff'?'selected':''}}>Staff</option></select>@error('type')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-6"><label class="form-label fw-medium">Issue date</label><input type="date" name="issue_date" class="form-control" value="{{$item->issue_date}}">@error('issue_date')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-12"><label class="form-label fw-medium">Expiry date</label><input type="date" name="expiry_date" class="form-control" value="{{$item->expiry_date}}">@error('expiry_date')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-4"><label class="form-label fw-medium">Status</label><select name="status" class="form-select"><option value="">Select...</option><option value="active" {{$item->status=='active'?'selected':''}}>Active</option><option value="expired" {{$item->status=='expired'?'selected':''}}>Expired</option></select>@error('status')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
</div></div></div>
<div class="my-4"><button type="submit" class="btn btn-gold me-2"><i class="bi bi-check-lg me-1"></i>Update</button><a href="{{route('admin.id-cards.index')}}" class="btn btn-outline-secondary">Cancel</a></div></form></div>
@endsection