@extends("layouts.admin")

@section("page-title","Dashboard")

@section("content")
<div class="container-fluid">

    <div class="row g-3 mb-4">
        <div class="col-xl-2 col-md-4 col-6"><div class="card border-0 shadow-sm h-100" style="border-top:3px solid #0d0d2b"><div class="card-body text-center py-3"><i class="bi bi-building fs-3 text-primary"></i><h3 class="fw-bold mt-2 mb-0">{{ $totalBranches }}</h3><small class="text-muted">Branches</small></div></div></div>
        <div class="col-xl-2 col-md-4 col-6"><div class="card border-0 shadow-sm h-100" style="border-top:3px solid #198754"><div class="card-body text-center py-3"><i class="bi bi-person-workspace fs-3 text-success"></i><h3 class="fw-bold mt-2 mb-0">{{ $totalTeachers }}</h3><small class="text-muted">Teachers</small></div></div></div>
        <div class="col-xl-2 col-md-4 col-6"><div class="card border-0 shadow-sm h-100" style="border-top:3px solid #c9a84c"><div class="card-body text-center py-3"><i class="bi bi-mortarboard fs-3" style="color:#c9a84c"></i><h3 class="fw-bold mt-2 mb-0">{{ $totalStudents }}</h3><small class="text-muted">Students</small></div></div></div>
        <div class="col-xl-2 col-md-4 col-6"><div class="card border-0 shadow-sm h-100" style="border-top:3px solid #dc3545"><div class="card-body text-center py-3"><i class="bi bi-journal-bookmark fs-3 text-danger"></i><h3 class="fw-bold mt-2 mb-0">{{ $totalClasses }}</h3><small class="text-muted">Classes</small></div></div></div>
        <div class="col-xl-2 col-md-4 col-6"><div class="card border-0 shadow-sm h-100" style="border-top:3px solid #6f42c1"><div class="card-body text-center py-3"><i class="bi bi-book fs-3" style="color:#6f42c1"></i><h3 class="fw-bold mt-2 mb-0">{{ $totalSubjects }}</h3><small class="text-muted">Subjects</small></div></div></div>
        <div class="col-xl-2 col-md-4 col-6"><div class="card border-0 shadow-sm h-100" style="border-top:3px solid #fd7e14"><div class="card-body text-center py-3"><i class="bi bi-calendar-range fs-3 text-warning"></i><h3 class="fw-bold mt-2 mb-0">{{ \App\Models\AcademicYear::count() }}</h3><small class="text-muted">Academic Yrs</small></div></div></div>
    </div>

    <div class="row mb-4"><div class="col-12"><div class="card border-0 shadow-sm"><div class="card-header py-3" style="background:#0d0d2b"><h6 class="mb-0 text-white"><i class="bi bi-lightning-fill me-2" style="color:#c9a84c"></i>Quick Actions</h6></div><div class="card-body py-3"><div class="d-flex flex-wrap gap-2"><a href="{{ route("admin.branches.create") }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-plus-lg me-1"></i>Add Branch</a><a href="{{ route("admin.teachers.create") }}" class="btn btn-sm btn-outline-success"><i class="bi bi-plus-lg me-1"></i>Add Teacher</a><a href="{{ route("admin.students.create") }}" class="btn btn-sm btn-outline-warning"><i class="bi bi-plus-lg me-1"></i>Add Student</a><a href="{{ route("admin.classrooms.create") }}" class="btn btn-sm btn-outline-danger"><i class="bi bi-plus-lg me-1"></i>Add Class</a><a href="{{ route("admin.subjects.create") }}" class="btn btn-sm" style="color:#6f42c1;border-color:#6f42c1"><i class="bi bi-plus-lg me-1"></i>Add Subject</a><a href="{{ route("admin.academic-years.create") }}" class="btn btn-sm btn-outline-dark"><i class="bi bi-plus-lg me-1"></i>New Academic Year</a><a href="{{ route("admin.terms.create") }}" class="btn btn-sm btn-outline-info"><i class="bi bi-plus-lg me-1"></i>New Term</a></div></div></div></div></div>

    <div class="row g-4">
        <div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-header py-3" style="background:#0d0d2b"><h6 class="mb-0 text-white"><i class="bi bi-clock-history me-2" style="color:#c9a84c"></i>Management Overview</h6></div><div class="card-body p-0"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Module</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>
        <tr><td><i class="bi bi-building me-2 text-primary"></i>Branches</td><td>{{ $totalBranches }}</td><td>@if($totalBranches>0)<span class="badge bg-success">Active</span>@else<span class="badge bg-secondary">Empty</span>@endif</td><td><a href="{{ route("admin.branches.index") }}" class="btn btn-sm btn-outline-primary">Manage</a></td></tr>
        <tr><td><i class="bi bi-person-workspace me-2 text-success"></i>Teachers</td><td>{{ $totalTeachers }}</td><td>@if($totalTeachers>0)<span class="badge bg-success">Active</span>@else<span class="badge bg-secondary">Empty</span>@endif</td><td><a href="{{ route("admin.teachers.index") }}" class="btn btn-sm btn-outline-success">Manage</a></td></tr>
        <tr><td><i class="bi bi-person me-2 text-warning"></i>Students</td><td>{{ $totalStudents }}</td><td>@if($totalStudents>0)<span class="badge bg-success">Active</span>@else<span class="badge bg-secondary">Empty</span>@endif</td><td><a href="{{ route("admin.students.index") }}" class="btn btn-sm btn-outline-warning">Manage</a></td></tr>
        <tr><td><i class="bi bi-journal-bookmark me-2 text-danger"></i>Classes</td><td>{{ $totalClasses }}</td><td>@if($totalClasses>0)<span class="badge bg-success">Active</span>@else<span class="badge bg-secondary">Empty</span>@endif</td><td><a href="{{ route("admin.classrooms.index") }}" class="btn btn-sm btn-outline-danger">Manage</a></td></tr>
        <tr><td><i class="bi bi-book me-2" style="color:#6f42c1"></i>Subjects</td><td>{{ $totalSubjects }}</td><td>@if($totalSubjects>0)<span class="badge bg-success">Active</span>@else<span class="badge bg-secondary">Empty</span>@endif</td><td><a href="{{ route("admin.subjects.index") }}" class="btn btn-sm" style="color:#6f42c1;border-color:#6f42c1">Manage</a></td></tr>
        <tr><td><i class="bi bi-calendar3 me-2 text-dark"></i>Academic Years</td><td>{{ \App\Models\AcademicYear::count() }}</td><td>@if($currentYear)<span class="badge bg-success">{{ $currentYear->name }}</span>@else<span class="badge bg-warning text-dark">None Set</span>@endif</td><td><a href="{{ route("admin.academic-years.index") }}" class="btn btn-sm btn-outline-dark">Manage</a></td></tr>
        </tbody></table></div></div></div>
        <div class="col-lg-4">
        @if($currentYear)<div class="card border-0 shadow-sm mb-4"><div class="card-header py-3" style="background:#198754"><h6 class="mb-0 text-white"><i class="bi bi-calendar-check me-2"></i>Current Academic Year</h6></div><div class="card-body text-center py-4"><h4 class="fw-bold" style="color:#198754">{{ $currentYear->name }}</h4>@if($currentYear->start_date)<p class="text-muted mb-0">{{ $currentYear->start_date }} to {{ $currentYear->end_date }}</p>@endif<a href="{{ route("admin.academic-years.index") }}" class="btn btn-sm btn-outline-success mt-2">View All</a></div></div>@endif
        <div class="card border-0 shadow-sm"><div class="card-header py-3" style="background:#c9a84c"><h6 class="mb-0 text-dark"><i class="bi bi-info-circle me-2"></i>System Info</h6></div><div class="card-body"><ul class="list-unstyled mb-0"><li class="d-flex justify-content-between py-1 border-bottom"><span class="text-muted">School</span><span class="fw-semibold">School of Redemption</span></li><li class="d-flex justify-content-between py-1 border-bottom"><span class="text-muted">Framework</span><span class="fw-semibold">Laravel 11</span></li><li class="d-flex justify-content-between py-1"><span class="text-muted">Branches</span><span class="fw-semibold">{{ $totalBranches }}</span></li></ul></div></div>
        </div>
    </div>
</div>
@endsection