<?php
namespace App\Http\Controllers\ProgressReport;use App\Http\Controllers\Controller;use App\Models\ProgressReport;use App\Models\ProgressReportSubject;use App\Models\Student;use App\Models\AcademicYear;use App\Models\Term;use App\Models\Classroom;use Illuminate\Http\Request;
class ProgressReportController extends Controller{
public function index(Request $r){$q=ProgressReport::with(["student","academicYear","term","classroom"]);if($r->filled("search")){$s=$r->search;$q->whereHas("student",function($x)use($s){$x->where("first_name","LIKE","%$s%")->orWhere("last_name","LIKE","%$s%");});}if($r->filled("academic_year_id"))$q->where("academic_year_id",$r->academic_year_id);if($r->filled("status"))$q->where("status",$r->status);$reports=$q->latest()->paginate(15);return view("admin.ProgressReport.index",compact("reports","totalReports",ProgressReport::count()));}
public function create(){$s=Student::where("status","active")->orderBy("first_name")->get();$ay=AcademicYear::orderBy("name")->get();$t=Term::orderBy("name")->get();$c=Classroom::orderBy("name")->get();return view("admin.ProgressReport.create",compact("s","ay","t","c"));}
public function store(Request $r){$v=$r->validate(["student_id"=>"required|exists:students,id","academic_year_id"=>"nullable","term_id"=>"nullable","classroom_id"=>"nullable","overall_grade"=>"nullable","total_marks"=>"nullable|numeric","max_marks"=>"nullable|numeric","class_rank"=>"nullable|integer","remarks"=>"nullable","teacher_comment"=>"nullable","status"=>"nullable|in:draft,published","subject_names"=>"nullable|array","subject_marks"=>"nullable|array","subject_max"=>"nullable|array","subject_grades"=>"nullable|array"]);$rep=ProgressReport::create(["student_id"=>$v["student_id"],"academic_year_id"=>$v["academic_year_id"]??null,"term_id"=>$v["term_id"]??null,"classroom_id"=>$v["classroom_id"]??null,"overall_grade"=>$v["overall_grade"]??null,"total_marks"=>$v["total_marks"]??0,"max_marks"=>$v["max_marks"]??100,"class_rank"=>$v["class_rank"]??null,"remarks"=>$v["remarks"]??null,"teacher_comment"=>$v["teacher_comment"]??null,"status"=>$v["status"]??"draft"]);if(!empty($v["subject_names"]))foreach($v["subject_names"] as $i=>$n){if(empty($n))continue;ProgressReportSubject::create(["progress_report_id"=>$rep->id,"subject_name"=>$n,"marks_obtained"=>$v["subject_marks"][$i]??0,"max_marks"=>$v["subject_max"][$i]??100,"grade"=>$v["subject_grades"][$i]??null]);}return redirect()->route("admin.progress-reports.index")->with("success","Report created.");}
public function edit(ProgressReport $p){$p->load("subjects");$s=Student::where("status","active")->orderBy("first_name")->get();$ay=AcademicYear::orderBy("name")->get();$t=Term::orderBy("name")->get();$c=Classroom::orderBy("name")->get();return view("admin.ProgressReport.edit",compact("p","s","ay","t","c"));}
public function update(Request $r,ProgressReport $p){$v=$r->validate(["student_id"=>"required|exists:students,id","academic_year_id"=>"nullable","term_id"=>"nullable","classroom_id"=>"nullable","overall_grade"=>"nullable","total_marks"=>"nullable|numeric","max_marks"=>"nullable|numeric","class_rank"=>"nullable|integer","remarks"=>"nullable","teacher_comment"=>"nullable","status"=>"nullable|in:draft,published,archived","subject_names"=>"nullable|array","subject_marks"=>"nullable|array","subject_max"=>"nullable|array","subject_grades"=>"nullable|array"]);$p->update(["student_id"=>$v["student_id"],"academic_year_id"=>$v["academic_year_id"]??null,"term_id"=>$v["term_id"]??null,"classroom_id"=>$v["classroom_id"]??null,"overall_grade"=>$v["overall_grade"]??null,"total_marks"=>$v["total_marks"]??0,"max_marks"=>$v["max_marks"]??100,"class_rank"=>$v["class_rank"]??null,"remarks"=>$v["remarks"]??null,"teacher_comment"=>$v["teacher_comment"]??null,"status"=>$v["status"]??"draft"]);$p->subjects()->delete();if(!empty($v["subject_names"]))foreach($v["subject_names"] as $i=>$n){if(empty($n))continue;ProgressReportSubject::create(["progress_report_id"=>$p->id,"subject_name"=>$n,"marks_obtained"=>$v["subject_marks"][$i]??0,"max_marks"=>$v["subject_max"][$i]??100,"grade"=>$v["subject_grades"][$i]??null]);}return redirect()->route("admin.progress-reports.index")->with("success","Report updated.");}
public function destroy(ProgressReport $p){$p->subjects()->delete();$p->delete();return redirect()->route("admin.progress-reports.index")->with("success","Report deleted.");}
}