<?php
/**
 * COMPLETE cPanel FIX SCRIPT
 * ----------------------------------------------------------------------------
 * Upload this file to your public/ folder.
 * Visit https://yourdomain.com/fix-all.php
 *
 * This script:
 * 1. Checks and fixes PHP upload limits (.user.ini)
 * 2. Creates all missing storage directories
 * 3. Fixes directory permissions (chmod 775)
 * 4. Creates the storage symlink
 * 5. Runs database migrations
 * 6. Clears all Laravel caches
 * 7. Tests image upload with GD
 * 8. Shows full diagnostic report
 *
 * ⚠️ DELETE THIS FILE after use!
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

$laravelRoot = dirname(__DIR__);
$publicRoot = __DIR__;

$results = [];

function logStep($category, $action, $status, $details = '') {
    global $results;
    $results[] = [
        'category' => $category,
        'action' => $action,
        'status' => $status,
        'details' => $details,
    ];
    $icon = $status === 'ok' ? '✅' : ($status === 'warn' ? '⚠️' : '❌');
    echo "<script>document.getElementById('log').innerHTML += '" . addslashes("$icon [$category] $action" . ($details ? ": $details" : "")) . "\\n';</script>";
    @ob_flush();
    @flush();
}

echo '<!DOCTYPE html><html><head><title>Fix All — cPanel</title>';
echo '<style>
body{font-family:monospace;padding:20px;max-width:1000px;margin:0 auto;background:#0f172a;color:#e2e8f0;}
h1{color:#10b981;}h2{color:#60a5fa;margin-top:20px;}
#log{background:#1e293b;border:1px solid #334155;border-radius:8px;padding:16px;font-size:12px;line-height:1.8;white-space:pre-wrap;min-height:400px;}
.summary{margin-top:20px;padding:16px;border-radius:8px;}
.ok{background:#064e3b;border:1px solid #10b981;}.err{background:#7f1d1d;border:1px solid #dc2626;}
.warning{background:#fef3c7;color:#92400e;padding:12px;border-radius:8px;margin-top:16px;}
code{background:#334155;padding:2px 6px;border-radius:4px;color:#fbbf24;}
</style></head><body>';
echo '<h1>🔧 Complete cPanel Fix Script</h1>';
echo '<p>Laravel Root: <code>' . $laravelRoot . '</code></p>';
echo '<p>Public Root: <code>' . $publicRoot . '</code></p>';
echo '<div id="log"></div>';
echo '<div id="summary"></div>';

@ob_flush();
@flush();

// ═══════════════════════════════════════════════════════════════════════
// STEP 1: Fix .user.ini (PHP upload limits)
// ═══════════════════════════════════════════════════════════════════════
echo '<h2>Step 1: Fix PHP Upload Limits (.user.ini)</h2>';

$userIniContent = <<<INI
; Redemption School — PHP Configuration
; Auto-generated by fix-all.php
upload_max_filesize = 60M
post_max_size = 65M
memory_limit = 256M
max_execution_time = 300
max_input_time = 120
session.gc_maxlifetime = 86400
session.gc_probability = 0
session.gc_divisor = 1
session.cookie_lifetime = 86400
session.use_strict_mode = 1
INI;

// Write .user.ini to public/ folder
$publicIniPath = $publicRoot . '/.user.ini';
$written1 = @file_put_contents($publicIniPath, $userIniContent);
if ($written1) {
    logStep('PHP Config', 'Create .user.ini in public/', 'ok', "Written {$written1} bytes");
} else {
    logStep('PHP Config', 'Create .user.ini in public/', 'err', 'Could not write — check permissions');
}

// Also write to project root (parent of public/)
$rootIniPath = $laravelRoot . '/.user.ini';
$written2 = @file_put_contents($rootIniPath, $userIniContent);
if ($written2) {
    logStep('PHP Config', 'Create .user.ini in project root', 'ok', "Written {$written2} bytes");
} else {
    logStep('PHP Config', 'Create .user.ini in project root', 'warn', 'Could not write — may not be needed');
}

// Verify current PHP limits
$currentUploadMax = ini_get('upload_max_filesize');
$currentPostMax = ini_get('post_max_size');
$currentMemory = ini_get('memory_limit');
logStep('PHP Config', 'Current limits', 'warn', "upload_max_filesize={$currentUploadMax}, post_max_size={$currentPostMax}, memory_limit={$currentMemory}");

if (returnBytes($currentUploadMax) < returnBytes('60M')) {
    logStep('PHP Config', 'Upload limit still low', 'warn', '.user.ini written but PHP has not reloaded yet. Use cPanel → MultiPHP Manager → change PHP version and change back to force reload.');
}

// ═══════════════════════════════════════════════════════════════════════
// STEP 2: Create all storage directories
// ═══════════════════════════════════════════════════════════════════════
echo '<h2>Step 2: Create Storage Directories</h2>';

$dirsToCreate = [
    'storage/app/public/team-photos',
    'storage/app/public/news-images',
    'storage/app/public/gallery',
    'storage/app/public/backups',
    'storage/framework/views',
    'storage/framework/sessions',
    'storage/framework/cache',
    'storage/framework/cache/data',
    'storage/logs',
    'bootstrap/cache',
    // Public fallback directories (for images without symlink)
    'public/team-photos',
    'public/news-images',
    'public/gallery',
];

foreach ($dirsToCreate as $dir) {
    $fullPath = $laravelRoot . '/' . $dir;
    if (is_dir($fullPath)) {
        logStep('Directories', "Exists: $dir", 'ok');
    } else {
        $created = @mkdir($fullPath, 0775, true);
        if ($created) {
            logStep('Directories', "Created: $dir", 'ok');
        } else {
            logStep('Directories', "Failed to create: $dir", 'err', error_get_last()['message'] ?? 'Unknown error');
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════
// STEP 3: Fix directory permissions
// ═══════════════════════════════════════════════════════════════════════
echo '<h2>Step 3: Fix Directory Permissions</h2>';

$dirsToChmod = [
    'storage/app',
    'storage/app/public',
    'storage/app/public/team-photos',
    'storage/app/public/news-images',
    'storage/app/public/gallery',
    'storage/framework',
    'storage/framework/views',
    'storage/framework/sessions',
    'storage/framework/cache',
    'storage/logs',
    'bootstrap/cache',
    'public/team-photos',
    'public/news-images',
    'public/gallery',
];

foreach ($dirsToChmod as $dir) {
    $fullPath = $laravelRoot . '/' . $dir;
    if (file_exists($fullPath)) {
        $currentPerms = substr(sprintf('%o', fileperms($fullPath)), -4);
        if (is_writable($fullPath)) {
            logStep('Permissions', "$dir ($currentPerms) — writable", 'ok');
        } else {
            $changed = @chmod($fullPath, 0775);
            if ($changed && is_writable($fullPath)) {
                logStep('Permissions', "$dir — fixed to 775", 'ok');
            } else {
                // Try 0777 as last resort
                @chmod($fullPath, 0777);
                if (is_writable($fullPath)) {
                    logStep('Permissions', "$dir — fixed to 777", 'warn', 'Used 777 — less secure but works');
                } else {
                    logStep('Permissions', "$dir — STILL NOT WRITABLE", 'err', 'Manual fix needed via cPanel File Manager');
                }
            }
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════
// STEP 4: Create storage symlink
// ═══════════════════════════════════════════════════════════════════════
echo '<h2>Step 4: Storage Symlink</h2>';

$symlinkPath = $publicRoot . '/storage';
$targetPath = $laravelRoot . '/storage/app/public';

if (is_link($symlinkPath)) {
    logStep('Symlink', 'public/storage symlink exists', 'ok');
} elseif (file_exists($symlinkPath)) {
    // It exists but is not a symlink (maybe a directory) — can't fix automatically
    logStep('Symlink', 'public/storage exists but is NOT a symlink', 'warn', 'Delete it manually via File Manager, then re-run this script');
} else {
    if (@symlink($targetPath, $symlinkPath)) {
        logStep('Symlink', 'Created public/storage → storage/app/public', 'ok');
    } else {
        logStep('Symlink', 'Could not create symlink', 'warn', 'cPanel may block symlink(). Images will use public/ fallback directories instead.');
    }
}

// ═══════════════════════════════════════════════════════════════════════
// STEP 5: Check GD extension
// ═══════════════════════════════════════════════════════════════════════
echo '<h2>Step 5: Check GD Extension</h2>';

if (extension_loaded('gd')) {
    $gdInfo = gd_info();
    logStep('GD', 'GD extension loaded', 'ok');
    logStep('GD', 'JPEG Support: ' . ($gdInfo['JPEG Support'] ? 'YES' : 'NO'), $gdInfo['JPEG Support'] ? 'ok' : 'err');
    logStep('GD', 'PNG Support: ' . ($gdInfo['PNG Support'] ? 'YES' : 'NO'), $gdInfo['PNG Support'] ? 'ok' : 'err');
    logStep('GD', 'GIF Support: ' . ($gdInfo['GIF Read Support'] ? 'YES' : 'NO'), $gdInfo['GIF Read Support'] ? 'ok' : 'err');
    logStep('GD', 'WebP Support: ' . ($gdInfo['WebP Support'] ? 'YES' : 'NO'), $gdInfo['WebP Support'] ? 'ok' : 'warn');
} else {
    logStep('GD', 'GD extension NOT loaded', 'err', 'Enable in cPanel → MultiPHP Manager → PHP Extensions → search "gd"');
}

// ═══════════════════════════════════════════════════════════════════════
// STEP 6: Test actual file write
// ═══════════════════════════════════════════════════════════════════════
echo '<h2>Step 6: Test File Write</h2>';

$testDirs = [
    'storage/app/public/team-photos',
    'public/team-photos',
    'storage/app/public/news-images',
    'public/news-images',
];

foreach ($testDirs as $dir) {
    $fullPath = $laravelRoot . '/' . $dir;
    $testFile = $fullPath . '/write_test_' . time() . '.txt';
    $written = @file_put_contents($testFile, 'test');
    if ($written) {
        logStep('Write Test', "$dir — writable", 'ok');
        @unlink($testFile);
    } else {
        logStep('Write Test', "$dir — CANNOT WRITE", 'err', 'Check ownership/permissions');
    }
}

// ═══════════════════════════════════════════════════════════════════════
// STEP 7: Run Laravel commands (if bootstrap works)
// ═══════════════════════════════════════════════════════════════════════
echo '<h2>Step 7: Laravel Commands</h2>';

$autoloadPath = $laravelRoot . '/vendor/autoload.php';
if (!file_exists($autoloadPath)) {
    logStep('Laravel', 'vendor/autoload.php not found', 'err', 'Run composer install or upload vendor/ folder');
} else {
    try {
        require $autoloadPath;
        $app = require_once $laravelRoot . '/bootstrap/app.php';
        $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
        $kernel->bootstrap();

        // Clear caches
        try {
            Illuminate\Support\Facades\Artisan::call('config:clear');
            logStep('Laravel', 'config:clear', 'ok');
        } catch (\Throwable $e) {
            logStep('Laravel', 'config:clear', 'warn', $e->getMessage());
        }

        try {
            Illuminate\Support\Facades\Artisan::call('route:clear');
            logStep('Laravel', 'route:clear', 'ok');
        } catch (\Throwable $e) {
            logStep('Laravel', 'route:clear', 'warn', $e->getMessage());
        }

        try {
            Illuminate\Support\Facades\Artisan::call('view:clear');
            logStep('Laravel', 'view:clear', 'ok');
        } catch (\Throwable $e) {
            logStep('Laravel', 'view:clear', 'warn', $e->getMessage());
        }

        // Run migrations
        try {
            Illuminate\Support\Facades\Artisan::call('migrate', ['--force' => true]);
            $output = Illuminate\Support\Facades\Artisan::output();
            logStep('Laravel', 'migrate', 'ok', trim($output));
        } catch (\Throwable $e) {
            logStep('Laravel', 'migrate', 'err', $e->getMessage());
        }

        // Create storage link via Artisan
        try {
            Illuminate\Support\Facades\Artisan::call('storage:link');
            logStep('Laravel', 'storage:link', 'ok');
        } catch (\Throwable $e) {
            logStep('Laravel', 'storage:link', 'warn', $e->getMessage());
        }

        // Database check
        try {
            $pdo = Illuminate\Support\Facades\DB::connection()->getPdo();
            $dbName = config('database.connections.mysql.database');
            logStep('Database', "Connected to {$dbName}", 'ok');

            // Check users table
            $userCount = Illuminate\Support\Facades\DB::table('users')->count();
            logStep('Database', "Users table: {$userCount} records", 'ok');

            // Check team_members table
            $tmCount = Illuminate\Support\Facades\DB::table('team_members')->count();
            logStep('Database', "Team members: {$tmCount} records", 'ok');
        } catch (\Throwable $e) {
            logStep('Database', 'DB error', 'err', $e->getMessage());
        }

    } catch (\Throwable $e) {
        logStep('Laravel', 'Bootstrap failed', 'err', $e->getMessage());
    }
}

// ═══════════════════════════════════════════════════════════════════════
// STEP 8: Summary
// ═══════════════════════════════════════════════════════════════════════
echo '<h2>📋 Summary</h2>';

$okCount = count(array_filter($results, fn($r) => $r['status'] === 'ok'));
$warnCount = count(array_filter($results, fn($r) => $r['status'] === 'warn'));
$errCount = count(array_filter($results, fn($r) => $r['status'] === 'err'));

$summaryClass = $errCount > 0 ? 'err' : ($warnCount > 0 ? 'ok' : 'ok');
echo "<div class='summary $summaryClass' style='background:" . ($errCount > 0 ? '#7f1d1d' : '#064e3b') . ";border:1px solid " . ($errCount > 0 ? '#dc2626' : '#10b981') . ";border-radius:8px;padding:16px;color:#fff;'>";
echo "<strong>Results:</strong> ✅ {$okCount} OK, ⚠️ {$warnCount} warnings, ❌ {$errCount} errors";
echo '</div>';

// Show current PHP limits
echo '<h2>📊 Current PHP Configuration</h2>';
echo '<table style="border-collapse:collapse;width:100%;color:#e2e8f0;">';
echo '<tr style="background:#334155;"><th style="padding:8px;border:1px solid #475569;">Setting</th><th style="padding:8px;border:1px solid #475569;">Value</th><th style="padding:8px;border:1px solid #475569;">Status</th></tr>';

$checks = [
    ['upload_max_filesize', '60M'],
    ['post_max_size', '65M'],
    ['memory_limit', '256M'],
    ['max_execution_time', '300'],
    ['max_input_time', '120'],
];

foreach ($checks as $check) {
    $current = ini_get($check[0]);
    $ok = returnBytes($current) >= returnBytes($check[1]);
    echo '<tr>';
    echo '<td style="padding:8px;border:1px solid #475569;">' . $check[0] . '</td>';
    echo '<td style="padding:8px;border:1px solid #475569;">' . $current . '</td>';
    echo '<td style="padding:8px;border:1px solid #475569;color:' . ($ok ? '#10b981' : '#dc2626') . ';">' . ($ok ? '✅ OK' : '❌ TOO LOW') . '</td>';
    echo '</tr>';
}
echo '</table>';

if ($errCount > 0 || returnBytes(ini_get('upload_max_filesize')) < returnBytes('60M')) {
    echo '<div class="warning">';
    echo '<strong>⚠️ Action needed:</strong><br>';
    echo 'If PHP limits are still low after running this script:<br>';
    echo '1. cPanel → MultiPHP Manager → change PHP version to 8.1 → Apply → change back to 8.2 → Apply<br>';
    echo '2. This forces PHP-FPM to reload and read the new .user.ini<br>';
    echo '3. Wait 2-3 minutes<br>';
    echo '4. Visit this script again to verify<br>';
    echo '</div>';
}

echo '<div class="warning" style="margin-top:16px;">';
echo '<strong>⚠️ SECURITY:</strong> Delete <code>fix-all.php</code> from your server NOW!';
echo '</div>';

echo '</body></html>';

function returnBytes($val) {
    $val = trim($val);
    if (empty($val)) return 0;
    $last = strtolower($val[strlen($val)-1]);
    $val = (int)$val;
    switch($last) {
        case 'g': $val *= 1024;
        case 'm': $val *= 1024;
        case 'k': $val *= 1024;
    }
    return $val;
}
