@extends("layouts.admin")
@section("page-title","New Payroll")
@section("content")
<div class="container-fluid py-4"><div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h4 class="fw-bold mb-1"><i class="bi bi-plus-circle me-2"></i>New Payroll</h4><nav aria-label="breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}" class="text-decoration-none text-muted">Dashboard</a></li><li class="breadcrumb-item"><a href="{{route('admin.payrolls.index')}}" class="text-decoration-none text-muted">Payrolls</a></li><li class="breadcrumb-item active text-gold">New</li></ol></nav></div></div>
<form method="POST" action="{{route('admin.payrolls.store')}}">@csrf
<div class="card border-0 shadow-sm"><div class="card-header bg-white py-3" style="border-top:3px solid #c9a84c;"><h5 class="mb-0 fw-semibold">Details</h5></div><div class="card-body"><div class="row g-3"><div class="col-md-6"><label class="form-label fw-medium">Employee id</label><input type="text" name="employee_id" class="form-control">@error('employee_id')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-4"><label class="form-label fw-medium">Month</label><select name="month" class="form-select"><option value="">Select...</option><option value="1">Jan</option><option value="2">Feb</option><option value="3">Mar</option><option value="4">Apr</option><option value="5">May</option><option value="6">Jun</option><option value="7">Jul</option><option value="8">Aug</option><option value="9">Sep</option><option value="10">Oct</option><option value="11">Nov</option><option value="12">Dec</option></select>@error('month')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-6"><label class="form-label fw-medium">Year</label><input type="number" name="year" class="form-control" step="any">@error('year')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-6"><label class="form-label fw-medium">Basic salary</label><input type="number" name="basic_salary" class="form-control" step="any">@error('basic_salary')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-12"><label class="form-label fw-medium">Allowances</label><input type="number" name="allowances" class="form-control" step="any">@error('allowances')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-12"><label class="form-label fw-medium">Deductions</label><input type="number" name="deductions" class="form-control" step="any">@error('deductions')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
<div class="col-md-4"><label class="form-label fw-medium">Status</label><select name="status" class="form-select"><option value="">Select...</option><option value="pending">Pending</option><option value="paid">Paid</option></select>@error('status')<div class="text-danger small mt-1">{{$message}}</div>@enderror</div>
</div></div></div>
<div class="my-4"><button type="submit" class="btn btn-gold me-2"><i class="bi bi-check-lg me-1"></i>Save</button><a href="{{route('admin.payrolls.index')}}" class="btn btn-outline-secondary">Cancel</a></div></form></div>
@endsection